version: '3.7'

services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=Passwd
      - MYSQL_USER=TpBlog
      - MYSQL_PASSWORD=TpBlog
    ports:
      - "3306:3306"
  phpapp:
    build: .
    ports:
      - "8088:80"
    depends_on:
      - mariadb
    volumes:
      - "./:/var/www/html"
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - "8082:80"
    depends_on:
      - mariadb